version: '3'

services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
    app:
        build: .
        depends_on:
            - mongo
        ports:
            - '3002:3002'
        environment:
            HOST: 'http://192.168.99.100'
            PORT: '3002'
            MONGO_URL: mongodb://192.168.99.100:27017/images
            STORAGE_TYPE: local
